### PR TITLE
Add convert methods and create simulation ready IDF

### LINKED ISSUE #80: Conversion methods between BHoM and EnergyPlus objects
#### Description:

Full list of EnergyPlus objects as defined in v9.2.0, most including keys and default values linked [**_here_**](https://github.com/BHoM/EnergyPlus_Toolkit/files/4696170/IDF_OBJECTS.json.txt). These were auto-generated using [Eppy](https://pypi.org/project/eppy/) so some parts may be missing, but this is for now the most comprehensive and **readable** set of objects we should be aiming to be able to create.

Where "_choice_" or "_real_" is listed as dtype, these would need to be referenced in the E+ documentation to create the corresponding `enum` to choose from (example [here](https://bigladdersoftware.com/epx/docs/9-2/input-output-reference/group-simulation-parameters.html#field-algorithm-2-000)), or set as `string` to allow user-set names.

### PR DESCRIPTION
**Pull request by tg359**
### Issues addressed by this PR

Closes #80 

Updated and added methods for converting BHoM Environment objects to EnergyPlus objects and their string representation for serialising into an IDF file ready to simulate.

### Test files

[_script.zip](https://github.com/BHoM/EnergyPlus_Toolkit/files/4815285/_script.zip)

### Additional comments

This PR is raised mainly as  a public version of the developments made. I'm not expecting it to be ready to merge but as a place where comments can be added and the general structure and operation of the code can be reviewed and changes suggested for now.

I'm very aware that much of the code herein would likely fail the CI/CD checks, but as a first pass at an MVP it functions and I'm hoping the automated checks can help me track down where it's currently non-compliant!

### CODE REVIEW

**Comment by tg359** [comment]
I should probably have mentioned above that there are a lot of placeholder files ready to populate with `IEnergyPlusClass` objects when they're needed - this is due to an automated export of objects available within the EnergyPlus 9.2.0 IDD that were used as the basis for creating the objects necessary to simulate using EnergyPlus.

**Comment by FraserGreenroyd** [comment]
I've run a check compliance check to check if it picks up on the Reference issue.

The references to Diffing_oM and Diffing_Engine used in this PR should be set to `C:\ProgramData...` rather than `..\..\..\..\ProgramData` to help CheckCore

**Pull request merged**
